### ISSUE TITLE
Cannot open display when attempting to use with Termux-X11

### ISSUE THREAD

**Issue by lmservas** [Yisus7u7/tmsd#1]
First of all this is so totally awesome!! Thanks so much for doing this. I attempted to use this with Termux-X11 by first following your install instructions and then substituting mate-session for xfce4 etc. and was met with the following:

❯ export XDG_RUNTIME_DIR=${TMPDIR}                                                                 ~
❯ termux-x11 :1 >/dev/null &                                                                       ~
[1] 4738
❯ res = 0                                                                                          ~
Activity is started
Got getWaylandFD
{ParcelFileDescriptor: java.io.FileDescriptor@455f91e}
Lorie requested fd
Got getLogFD
{ParcelFileDescriptor: java.io.FileDescriptor@5b665ff}
Got finish request
App sent finishing command
Starting Xwayland
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/Xwayland": cannot locate symbol "ffi_type_uint32" referenced by "/data/data/com.termux/files/usr/lib/libwayland-client.so"...

[1]  + 4738 exit 1     termux-x11 :1 > /dev/null
❯ env DISPLAY=:1 mate-session                                                                      ~

** (mate-session:5196): WARNING **: 00:05:26.480: Cannot open display:
1 ❯                                                                                                ~

I'm not sure if this belongs here or over at the Termux-X11 Repo so I'm sorry if this is not appropriate. Thanks!!

**Comment by lmservas** [comment]
Okay I installed your xfce4 desktop environment in order to test against this and can confirm the issue is with xwayland)/Termux-X11. My apologies. Will close.

**Comment by JesusChapman** [comment]
Xwayland is broken.. Update your packages
